# Generated by Django 4.2.6 on 2023-11-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cursos/')),
            ],
        ),
    ]
