# Generated by Django 4.2.6 on 2023-11-14 22:46

import curso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='cursos/', validators=[curso.models.validate_any_file]),
        ),
    ]
